# **PyTorch Tensors**

---

## **What are Tensors?**

Tensors are a specialized data structure similar to arrays and matrices. In PyTorch, tensors are used to encode inputs, outputs, and model parameters. They support hardware acceleration (GPU/TPU), automatic differentiation, and can share memory with NumPy arrays.

Reference: [PyTorch Tensor Basics](https://docs.pytorch.org/tutorials/beginner/basics/tensorqs_tutorial.html)

### Importing PyTorch and Checking Version

PyTorch must be imported before use. The version helps ensure compatibility with features and APIs.

In [1]:
# Import PyTorch and check version
import torch

print(torch.__version__)  # Print PyTorch version

2.8.0+cpu


### Checking for GPU Availability

PyTorch can use GPUs for faster computation. This code checks if a GPU is available and prints device info.

In [2]:
# Check if GPU is available and print device info
if torch.cuda.is_available():
    print("GPU is available!")
    print(f"Using GPU: {torch.cuda.get_device_name(0)}")
else:
    print("GPU not available. Using CPU.")

GPU not available. Using CPU.


## **Creating Tensors**

PyTorch provides multiple ways to create tensors. Below are some commonly used methods.

### Creating an Uninitialized Tensor

`torch.empty()` creates a tensor with uninitialized values. Useful for allocating memory quickly.

In [3]:
# Create an uninitialized tensor of shape (2, 3)
a = torch.empty(2, 3)
a

tensor([[0., 0., 0.],
        [0., 0., 0.]])

### Checking Tensor Type

Use `type()` to check the type of a tensor object.

In [4]:
# Check the type of tensor 'a'
type(a)

torch.Tensor

### Creating a Tensor of Zeros

`torch.zeros()` creates a tensor filled with zeros. Useful for initialization.

In [5]:
# Create a tensor of zeros with shape (3, 2)
torch.zeros(3, 2)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

### Creating a Tensor of Ones

`torch.ones()` creates a tensor filled with ones. Useful for initialization.

In [6]:
# Create a tensor of ones with shape (2, 3)
torch.ones(2, 3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

### Creating a Random Tensor

`torch.rand()` creates a tensor with random values between 0 and 1.

In [7]:
# Create a random tensor of shape (3, 2)
torch.rand(3, 2)

tensor([[0.9934, 0.7444],
        [0.6559, 0.6401],
        [0.8392, 0.8900]])

### Setting a Manual Seed for Randomness

`torch.manual_seed()` sets the seed for generating random numbers, ensuring reproducibility.

In [8]:
# Set manual seed for reproducibility
torch.manual_seed(100)
torch.rand(3, 2)

tensor([[0.1117, 0.8158],
        [0.2626, 0.4839],
        [0.6765, 0.7539]])

### Repeating Random Tensor with Same Seed

Setting the same seed again produces the same random tensor.

In [9]:
# Repeating with the same seed gives the same result
torch.manual_seed(100)
torch.rand(3, 2)

tensor([[0.1117, 0.8158],
        [0.2626, 0.4839],
        [0.6765, 0.7539]])

### Creating a Tensor from a List

`torch.tensor()` creates a tensor from a Python list or nested lists.

In [10]:
# Create a tensor from a nested list
torch.tensor([[1, 2, 3], [4, 5, 6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

### Creating Tensors with arange, linspace, eye, and full

`torch.arange()` creates sequences, `torch.linspace()` creates evenly spaced values, `torch.eye()` creates identity matrices, and `torch.full()` creates tensors filled with a specific value.

In [11]:
# Using arange to create sequences
print("using arange ->", torch.arange(0, 10))
print("\n\nusing arange ->", torch.arange(0, 10, 1))
print("\n\nusing arange ->", torch.arange(0, 10, 2))
print("\n\nusing arange ->", torch.arange(0, 10, 5))

using arange -> tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


using arange -> tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


using arange -> tensor([0, 2, 4, 6, 8])


using arange -> tensor([0, 5])


### Creating Evenly Spaced Values with linspace

`torch.linspace()` creates a tensor with evenly spaced values between two endpoints.

In [12]:
# Using linspace for evenly spaced values
print("using linspace ->", torch.linspace(0, 10, 0))
print("\n\nusing linspace ->", torch.linspace(0, 10, 1))
print("\n\nusing linspace ->", torch.linspace(0, 10, 5))
print("\n\nusing linspace ->", torch.linspace(0, 10, 10))

using linspace -> tensor([])


using linspace -> tensor([0.])


using linspace -> tensor([ 0.0000,  2.5000,  5.0000,  7.5000, 10.0000])


using linspace -> tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])


### Creating Identity Matrices with eye

`torch.eye()` creates an identity matrix of given size.

In [13]:
# Using eye for identity matrices
print("using eye ->", torch.eye(1))
print("\n\nusing eye ->", torch.eye(2))
print("\n\nusing eye ->", torch.eye(5))

using eye -> tensor([[1.]])


using eye -> tensor([[1., 0.],
        [0., 1.]])


using eye -> tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])


### Creating Tensors Filled with a Specific Value

`torch.full()` creates a tensor filled with a specified value.

In [14]:
# Using full to create tensors filled with a specific value
print("using full ->", torch.full((2, 2), 10))
print("\n\nusing full ->", torch.full((3, 3), 5))

using full -> tensor([[10, 10],
        [10, 10]])


using full -> tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


## **Tensor Shape**

The shape of a tensor describes its dimensions.

In [15]:
# Create a tensor and check its shape
x = torch.tensor([[1, 2, 3], [4, 5, 6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [16]:
# Get the shape of tensor 'x'
x.shape

torch.Size([2, 3])

### Creating Tensors Like Another Tensor

You can create tensors with the same shape as an existing tensor using `empty_like`, `zeros_like`, `ones_like`, and `rand_like`.

In [17]:
# Create an empty tensor with the same shape as 'x'
torch.empty_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [18]:
# Create a zeros tensor with the same shape as 'x'
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [19]:
# Create a ones tensor with the same shape as 'x'
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [20]:
# Create a random tensor with the same shape as 'x' and float32 dtype
torch.rand_like(x, dtype=torch.float32)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

## **Tensor Data Types (dtypes)**

PyTorch tensors can have different data types, which affect precision and memory usage.

In [21]:
# Find the data type of tensor 'x'
x.dtype

torch.int64

In [22]:
# Assign a specific data type to a tensor
torch.tensor([1.0, 2.0, 3.0], dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [23]:
# Assign float64 data type
torch.tensor([1, 2, 3], dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [24]:
# Convert tensor 'x' to float32 using .to()
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

### **Common PyTorch Data Types**

| Data Type | Dtype | Description |
|-----------|-------|-------------|
| 32-bit Floating Point | `torch.float32` | Standard for deep learning |
| 64-bit Floating Point | `torch.float64` | Double precision |
| 16-bit Floating Point | `torch.float16` | Half precision |
| BFloat16 | `torch.bfloat16` | Used on TPUs |
| 8-bit Integer | `torch.int8` | Quantized models |
| 16-bit Integer | `torch.int16` | Intermediate precision |
| 32-bit Integer | `torch.int32` | Standard integer |
| 64-bit Integer | `torch.int64` | Large numbers |
| 8-bit Unsigned Integer | `torch.uint8` | Image data |
| Boolean | `torch.bool` | True/False |
| Complex 64 | `torch.complex64` | Scientific tasks |
| Complex 128 | `torch.complex128` | High precision |
| Quantized Integer | `torch.qint8` | Efficient inference |
| Quantized Unsigned Integer | `torch.quint8` | Image tasks |

## **Mathematical Operations on Tensors**

PyTorch supports a wide range of mathematical operations. Let's explore them step by step.

### **1. Scalar Operations**

Operations performed with a scalar value on all elements of a tensor.

In [25]:
# Create a random tensor
x = torch.rand(2, 2)
x

tensor([[0.7118, 0.7876],
        [0.4183, 0.9014]])

In [26]:
# Addition with scalar
x = x + 2
x

tensor([[2.7118, 2.7876],
        [2.4183, 2.9014]])

In [27]:
# Subtraction with scalar
x = x - 2
x

tensor([[0.7118, 0.7876],
        [0.4183, 0.9014]])

In [28]:
# Multiplication with scalar
x = x * 3
x

tensor([[2.1353, 2.3627],
        [1.2549, 2.7042]])

In [29]:
# Division with scalar
x = x / 3
x

tensor([[0.7118, 0.7876],
        [0.4183, 0.9014]])

In [30]:
# Integer division
x = (x * 100)//3
x

tensor([[23., 26.],
        [13., 30.]])

In [31]:
# Modulo operation
x = ((x * 100)//3) % 2
x

tensor([[0., 0.],
        [1., 0.]])

In [32]:
# Power operation
x = x**2
x

tensor([[0., 0.],
        [1., 0.]])

### **2. Element-wise Operations**

Operations performed between tensors of the same shape.

In [33]:
# Create two random tensors of same shape and dtype
a = torch.rand(2, 3, dtype=torch.float64)
b = torch.rand(2, 3, dtype=torch.float64)
print(a)
print()
print(b)

tensor([[0.9751, 0.7911, 0.4274],
        [0.4460, 0.5522, 0.9559]], dtype=torch.float64)

tensor([[0.9405, 0.2215, 0.3271],
        [0.1352, 0.6283, 0.3030]], dtype=torch.float64)


In [34]:
# Element-wise addition
a + b

tensor([[1.9156, 1.0127, 0.7544],
        [0.5811, 1.1805, 1.2589]], dtype=torch.float64)

In [35]:
# Element-wise subtraction
a - b

tensor([[ 0.0346,  0.5696,  0.1003],
        [ 0.3108, -0.0761,  0.6528]], dtype=torch.float64)

In [36]:
# Element-wise multiplication
a * b

tensor([[0.9170, 0.1752, 0.1398],
        [0.0603, 0.3469, 0.2897]], dtype=torch.float64)

In [37]:
# Element-wise division
a / b

tensor([[1.0368, 3.5716, 1.3065],
        [3.2986, 0.8789, 3.1544]], dtype=torch.float64)

In [38]:
# Element-wise power
a ** b

tensor([[0.9766, 0.9494, 0.7572],
        [0.8966, 0.6886, 0.9864]], dtype=torch.float64)

In [39]:
# Element-wise modulo
a % b

tensor([[0.0346, 0.1266, 0.1003],
        [0.0404, 0.5522, 0.0468]], dtype=torch.float64)

In [40]:
# Absolute value
c = torch.tensor([1, -2, 3, -4])
torch.abs(c)

tensor([1, 2, 3, 4])

In [41]:
# Negative value
torch.neg(c)

tensor([-1,  2, -3,  4])

In [42]:
# Rounding values
d = torch.tensor([1.9, 2.3, 3.7, 4.4])
torch.round(d)

tensor([2., 2., 4., 4.])

In [43]:
# Ceiling values
d = torch.tensor([1.9, 2.3, 3.7, 4.4])
torch.ceil(d)

tensor([2., 3., 4., 5.])

In [44]:
# Floor values
d = torch.tensor([1.9, 2.3, 3.7, 4.4])
torch.floor(d)

tensor([1., 2., 3., 4.])

In [45]:
# Clamp values between min and max
d = torch.tensor([1.9, 2.3, 3.7, 4.4])
torch.clamp(d, min=2, max=3)

tensor([2.0000, 2.3000, 3.0000, 3.0000])

### **3. Reduction Operations**

Operations that reduce the tensor to a single value or along a dimension.

In [46]:
# Create a random integer tensor
e = torch.randint(size=(2, 3), low=1, high=10, dtype=torch.float32)
e

tensor([[7., 6., 7.],
        [4., 1., 7.]])

In [47]:
# Sum of all elements
torch.sum(e)

tensor(32.)

In [48]:
# Sum along columns (dim=0)
torch.sum(e, dim=0)

tensor([11.,  7., 14.])

In [49]:
# Sum along rows (dim=1)
torch.sum(e, dim=1)

tensor([20., 12.])

In [50]:
# Mean of all elements
torch.mean(e)

tensor(5.3333)

In [51]:
# Mean along columns
torch.mean(e, dim=0)

tensor([5.5000, 3.5000, 7.0000])

In [52]:
# Mean along rows
torch.mean(e, dim=1)

tensor([6.6667, 4.0000])

In [53]:
# Median value
torch.median(e)

tensor(6.)

In [54]:
# Maximum value
torch.max(e)

tensor(7.)

In [55]:
# Minimum value
torch.min(e)

tensor(1.)

In [56]:
# Product of all elements
torch.prod(e)

tensor(8232.)

In [57]:
# Standard deviation
torch.std(e)

tensor(2.4221)

In [58]:
# Variance
torch.var(e)

tensor(5.8667)

In [59]:
# Index of maximum value
torch.argmax(e)

tensor(0)

In [60]:
# Index of minimum value
torch.argmin(e)

tensor(4)

### **4. Matrix Operations**

Matrix multiplication, dot product, transpose, determinant, and inverse.

In [61]:
# Create two matrices for multiplication
f = torch.randint(size=(2, 3), low=1, high=10)
g = torch.randint(size=(3, 2), low=1, high=10)
print(f)
print()
print(g)

tensor([[5, 4, 7],
        [2, 1, 1]])

tensor([[4, 6],
        [6, 6],
        [1, 4]])


In [62]:
# Matrix multiplication
torch.matmul(f, g)

tensor([[51, 82],
        [15, 22]])

In [63]:
# Dot product of vectors
vector1 = torch.tensor([1, 2])
vector2 = torch.tensor([3, 4])
torch.dot(vector1, vector2)

tensor(11)

In [64]:
# Transpose a matrix
torch.transpose(f, 0, 1)

tensor([[5, 2],
        [4, 1],
        [7, 1]])

In [65]:
# Determinant and inverse of a square matrix
h = torch.randint(size=(3, 3), low=1, high=10, dtype=torch.float32)
h

tensor([[1., 3., 7.],
        [2., 2., 8.],
        [4., 1., 1.]])

In [66]:
# Determinant
torch.det(h)

tensor(42.0000)

In [67]:
# Inverse
torch.inverse(h)

tensor([[-0.1429,  0.0952,  0.2381],
        [ 0.7143, -0.6429,  0.1429],
        [-0.1429,  0.2619, -0.0952]])

### **5. Comparison Operations**

Element-wise comparison between tensors.

In [68]:
# Create two tensors for comparison
i = torch.randint(size=(2, 3), low=0, high=10)
j = torch.randint(size=(2, 3), low=0, high=10)
print(i)
print(j)

tensor([[3, 3, 5],
        [0, 6, 4]])
tensor([[0, 8, 4],
        [7, 2, 3]])


In [69]:
# Greater than
i > j

tensor([[ True, False,  True],
        [False,  True,  True]])

In [70]:
# Less than
i < j

tensor([[False,  True, False],
        [ True, False, False]])

In [71]:
# Equal to
i == j

tensor([[False, False, False],
        [False, False, False]])

In [72]:
# Not equal to
i != j

tensor([[True, True, True],
        [True, True, True]])

In [73]:
# Greater than or equal to
i >= j

tensor([[ True, False,  True],
        [False,  True,  True]])

In [74]:
# Less than or equal to
i <= j

tensor([[False,  True, False],
        [ True, False, False]])

### **6. Special Functions**

PyTorch provides many mathematical functions such as log, exp, sqrt, sigmoid, softmax, and relu.

In [75]:
# Create a tensor for special functions
k = torch.randint(size=(2, 3), low=1, high=10, dtype=torch.float32)
k

tensor([[6., 3., 9.],
        [4., 6., 7.]])

In [76]:
# Natural logarithm
torch.log(k)

tensor([[1.7918, 1.0986, 2.1972],
        [1.3863, 1.7918, 1.9459]])

In [77]:
# Exponential
torch.exp(k)

tensor([[ 403.4288,   20.0855, 8103.0840],
        [  54.5981,  403.4288, 1096.6332]])

In [78]:
# Square root
torch.sqrt(k)

tensor([[2.4495, 1.7321, 3.0000],
        [2.0000, 2.4495, 2.6458]])

In [79]:
# Sigmoid activation
torch.sigmoid(k)

tensor([[0.9975, 0.9526, 0.9999],
        [0.9820, 0.9975, 0.9991]])

In [80]:
# Softmax activation along dim=0
torch.softmax(k, dim=0)

tensor([[0.8808, 0.0474, 0.8808],
        [0.1192, 0.9526, 0.1192]])

In [81]:
# ReLU activation
torch.relu(k)

tensor([[6., 3., 9.],
        [4., 6., 7.]])

## **Inplace Operations**

Inplace operations modify the original tensor and are denoted by a trailing underscore (e.g., `add_`, `relu_`).

In [82]:
# Create two random tensors
m = torch.rand(2, 3)
n = torch.rand(2, 3)
print(m)
print(n)

tensor([[0.2855, 0.2324, 0.9141],
        [0.7668, 0.1659, 0.4393]])
tensor([[0.2243, 0.8935, 0.0497],
        [0.1780, 0.3011, 0.1893]])


In [83]:
# Inplace addition: modifies 'm'
m.add_(n)

tensor([[0.5098, 1.1259, 0.9638],
        [0.9448, 0.4670, 0.6286]])

In [84]:
# Check 'm' after inplace addition
m

tensor([[0.5098, 1.1259, 0.9638],
        [0.9448, 0.4670, 0.6286]])

In [85]:
# 'n' remains unchanged
n

tensor([[0.2243, 0.8935, 0.0497],
        [0.1780, 0.3011, 0.1893]])

In [86]:
# ReLU (not inplace)
torch.relu(m)

tensor([[0.5098, 1.1259, 0.9638],
        [0.9448, 0.4670, 0.6286]])

In [87]:
# Inplace ReLU
m.relu_()

tensor([[0.5098, 1.1259, 0.9638],
        [0.9448, 0.4670, 0.6286]])

In [88]:
# Check 'm' after inplace ReLU
m

tensor([[0.5098, 1.1259, 0.9638],
        [0.9448, 0.4670, 0.6286]])

## **Copying a Tensor**

Assignment creates a reference, not a copy. Use `.clone()` for a true copy.

In [89]:
# Create a random tensor
a = torch.rand(2, 3)
a

tensor([[0.9186, 0.2131, 0.3957],
        [0.6017, 0.4234, 0.5224]])

In [90]:
# Assignment: 'b' is a reference to 'a'
b = a

In [91]:
# Show 'b'
b

tensor([[0.9186, 0.2131, 0.3957],
        [0.6017, 0.4234, 0.5224]])

In [92]:
# Modify 'a' and see effect on 'b'
a[0][0] = 0

In [93]:
# Show 'a'
a

tensor([[0.0000, 0.2131, 0.3957],
        [0.6017, 0.4234, 0.5224]])

In [94]:
# Show 'b' (also changed)
b

tensor([[0.0000, 0.2131, 0.3957],
        [0.6017, 0.4234, 0.5224]])

In [95]:
# Check memory id of 'a'
id(a)

2735085742144

In [96]:
# Check memory id of 'b' (same as 'a')
id(b)

2735085742144

In [97]:
# Clone 'a' to create a true copy
b = a.clone()

In [98]:
# Show 'a'
a

tensor([[0.0000, 0.2131, 0.3957],
        [0.6017, 0.4234, 0.5224]])

In [99]:
# Show 'b' (independent copy)
b

tensor([[0.0000, 0.2131, 0.3957],
        [0.6017, 0.4234, 0.5224]])

In [100]:
# Modify 'a' and check 'b'
a[0][0] = 10

In [101]:
# Show 'a'
a

tensor([[10.0000,  0.2131,  0.3957],
        [ 0.6017,  0.4234,  0.5224]])

In [102]:
# Show 'b' (unchanged)
b

tensor([[0.0000, 0.2131, 0.3957],
        [0.6017, 0.4234, 0.5224]])

In [103]:
# Check memory id of 'a'
id(a)

2735085742144

In [104]:
# Check memory id of 'b' (different from 'a')
id(b)

2735085680048

In [105]:
# Clone again for demonstration
b = a.clone()

In [106]:
# Show 'a'
a

tensor([[10.0000,  0.2131,  0.3957],
        [ 0.6017,  0.4234,  0.5224]])

In [107]:
# Show 'b'
b

tensor([[10.0000,  0.2131,  0.3957],
        [ 0.6017,  0.4234,  0.5224]])

In [108]:
# Modify 'a' again
a[0][0] = 15
a

tensor([[15.0000,  0.2131,  0.3957],
        [ 0.6017,  0.4234,  0.5224]])

In [109]:
# Show 'b' (still unchanged)
b

tensor([[10.0000,  0.2131,  0.3957],
        [ 0.6017,  0.4234,  0.5224]])

In [110]:
# Check memory id of 'a'
id(a)

2735085742144

In [111]:
# Check memory id of 'b'
id(b)

2735085680208

## **Reshaping Tensors**

PyTorch provides several methods to reshape tensors, including `reshape`, `flatten`, `permute`, `unsqueeze`, and `squeeze`.

In [112]:
# Create a tensor of ones
a = torch.ones(4, 4)
a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [113]:
# Reshape to (2, 2, 2, 2)
a.reshape(2, 2, 2, 2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [114]:
# Flatten to 1D
a.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [115]:
# Create a random tensor of shape (2, 3, 4)
b = torch.rand(2, 3, 4)
b

tensor([[[0.4175, 0.0340, 0.9157, 0.3079],
         [0.6269, 0.8277, 0.6594, 0.0887],
         [0.4890, 0.5887, 0.7340, 0.8497]],

        [[0.9112, 0.4847, 0.9436, 0.3904],
         [0.2499, 0.3206, 0.9753, 0.7582],
         [0.6688, 0.2651, 0.2336, 0.5057]]])

In [116]:
# Check shape
b.shape

torch.Size([2, 3, 4])

In [117]:
# Permute dimensions
b.permute(2, 0, 1)

tensor([[[0.4175, 0.6269, 0.4890],
         [0.9112, 0.2499, 0.6688]],

        [[0.0340, 0.8277, 0.5887],
         [0.4847, 0.3206, 0.2651]],

        [[0.9157, 0.6594, 0.7340],
         [0.9436, 0.9753, 0.2336]],

        [[0.3079, 0.0887, 0.8497],
         [0.3904, 0.7582, 0.5057]]])

In [118]:
# Check permuted shape
b.permute(2, 0, 1).shape

torch.Size([4, 2, 3])

In [119]:
# Unsqueeze: add a dimension at position 0
c = torch.rand(226, 226, 3) # typical image size
c.unsqueeze(0).shape

torch.Size([1, 226, 226, 3])

In [120]:
# Squeeze: remove dimension at position 0 if size is 1
d = torch.rand(1, 20)
d.squeeze(0).shape

torch.Size([20])

## **NumPy and PyTorch Interoperability**

PyTorch tensors can be converted to NumPy arrays and vice versa. They share memory, so changes in one reflect in the other unless cloned.

In [121]:
# Create a PyTorch tensor
a = torch.tensor([1, 2, 3])
a

tensor([1, 2, 3])

In [122]:
# Convert to NumPy array
b = a.numpy()
b

array([1, 2, 3])

In [123]:
# Check type
type(b)

numpy.ndarray

In [124]:
# Create a NumPy array
import numpy as np
c = np.array([1, 2, 3])
c

array([1, 2, 3])

In [125]:
# Convert NumPy array to PyTorch tensor
d = torch.from_numpy(c)
d

tensor([1, 2, 3])

In [126]:
# Check type
type(d)

torch.Tensor

----
----