# **PyTorch Training Pipeline**


### Importing Required Libraries

We import PyTorch for tensor operations and deep learning, NumPy and pandas for data manipulation, and scikit-learn for preprocessing and splitting the dataset.

In [1]:
import torch
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

### Loading the Dataset

Read the breast cancer dataset from a CSV file using pandas.

In [2]:
df = pd.read_csv(
    'https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')

df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

### Checking Dataset Shape

Display the shape (rows, columns) of the loaded DataFrame.

In [3]:
df.shape

(569, 33)

### Dropping Unnecessary Columns

Remove columns that are not useful for training (`id` and `Unnamed: 32`).

In [4]:
df.drop(columns=['id', 'Unnamed: 32'], inplace=True)

### Displaying the Updated DataFrame

Show the first few rows after dropping columns.

In [5]:
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

### Checking Updated Shape

Display the shape of the DataFrame after dropping columns.

In [6]:
df.shape

(569, 31)

## **Train Test Split**


### Splitting Data into Train and Test Sets

Use `train_test_split` to divide the data into training and testing sets.

In [7]:
X_train, X_test, y_train, y_test = train_test_split(
    df.iloc[:, 1:], 
    df.iloc[:, 0], 
    test_size=0.2
)

# **Scaling**


### Feature Scaling

Standardize features by removing the mean and scaling to unit variance using `StandardScaler`.

In [8]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

### Displaying Scaled Training Features

Show the scaled training feature matrix.

In [9]:
X_train

array([[-1.01660769,  0.89786281, -1.0219767 , ..., -1.25917371,
        -1.08087326, -0.87691208],
       [-0.86292942, -0.5047364 , -0.84393523, ..., -0.2948223 ,
        -0.1986755 ,  1.83867715],
       [-0.61425004, -1.01220948, -0.60196069, ..., -1.01148226,
         0.35010575, -0.42662163],
       ...,
       [ 0.12061149,  0.53135447,  0.21460222, ...,  2.34601228,
         2.16874128,  2.43131033],
       [-1.34547918,  0.62768038, -1.33921423, ..., -1.34385067,
        -0.74905204, -0.5357326 ],
       [-0.7399868 , -0.19226455, -0.76179337, ..., -0.74311213,
        -0.26248727, -1.03753228]], shape=(455, 30))

### Displaying Training Labels

Show the training labels before encoding.

In [10]:
y_train

299    B
507    B
349    B
383    B
318    B
      ..
499    M
87     M
26     M
553    B
251    B
Name: diagnosis, Length: 455, dtype: object

# **Label Encoding**


### Label Encoding

Convert categorical labels to numeric values using `LabelEncoder`.

In [11]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

### Displaying Encoded Training Labels

Show the encoded training labels.

In [12]:
y_train

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1,
       1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1,

# **Numpy arrays to PyTorch tensors**


### Converting Numpy Arrays to PyTorch Tensors

Convert the processed NumPy arrays to PyTorch tensors for model training.

In [13]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)

y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

### Displaying Training Features Tensor

Show the PyTorch tensor containing training features.

In [14]:
X_train_tensor

tensor([[-1.0166,  0.8979, -1.0220,  ..., -1.2592, -1.0809, -0.8769],
        [-0.8629, -0.5047, -0.8439,  ..., -0.2948, -0.1987,  1.8387],
        [-0.6143, -1.0122, -0.6020,  ..., -1.0115,  0.3501, -0.4266],
        ...,
        [ 0.1206,  0.5314,  0.2146,  ...,  2.3460,  2.1687,  2.4313],
        [-1.3455,  0.6277, -1.3392,  ..., -1.3439, -0.7491, -0.5357],
        [-0.7400, -0.1923, -0.7618,  ..., -0.7431, -0.2625, -1.0375]],
       dtype=torch.float64)

### Checking Shape of Training Features Tensor

Display the shape of the training features tensor.

In [15]:
X_train_tensor.shape

torch.Size([455, 30])

### Displaying Training Labels Tensor

Show the PyTorch tensor containing training labels.

In [16]:
y_train_tensor

tensor([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0,
        0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0,
        1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0,
        0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1,
        0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
        0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0,
        1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0,
        0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0,
        0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0,
        1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0,
        0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1,
        0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1,
        0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0,

### Checking Shape of Training Labels Tensor

Display the shape of the training labels tensor.

In [17]:
y_train_tensor.shape

torch.Size([455])

# **Defining The Model**


### Defining the Model

Create a simple neural network class with weights, bias, forward pass, and loss function using PyTorch tensors.

In [18]:
class MySimpleNN():

    def __init__(self, X):

        self.weights = torch.rand(
            # Weight matrix would be of 30x1
            X.shape[1], 
            1, 
            dtype=torch.float64, 
            requires_grad=True
        )
        
        self.bias = torch.zeros(
            # Since we have only one neuron, therefore we require only one bais
            1, 
            dtype=torch.float64, 
            requires_grad=True
        )
        

    def forward(self, X):
        z = torch.matmul(X, self.weights) + self.bias
        y_pred = torch.sigmoid(z)
        return y_pred
    

    def loss_function(self, y_pred, y):
        # Clamp predictions to avoid log(0)
        epsilon = 1e-7
        y_pred = torch.clamp(y_pred, epsilon, 1 - epsilon)

        # Calculate loss
        loss = -(y_train_tensor * torch.log(y_pred) +
                 (1 - y_train_tensor) * torch.log(1 - y_pred)).mean()
        
        return loss

### Creating the Model Instance

Instantiate the neural network model with training features.

In [19]:
# create model
model = MySimpleNN(X_train_tensor)

### Setting Hyperparameters

Define the learning rate and number of epochs for training.

In [20]:
learning_rate = 0.1

epochs = 50

### Viewing Model Weights

Display the initial weights of the model.

In [21]:
model.weights

tensor([[0.5104],
        [0.5844],
        [0.1192],
        [0.0661],
        [0.7860],
        [0.0805],
        [0.0147],
        [0.0812],
        [0.8439],
        [0.7910],
        [0.7021],
        [0.0536],
        [0.9763],
        [0.2317],
        [0.2232],
        [0.5290],
        [0.6019],
        [0.7191],
        [0.4397],
        [0.0325],
        [0.0356],
        [0.6091],
        [0.9186],
        [0.2442],
        [0.4404],
        [0.3990],
        [0.5317],
        [0.6630],
        [0.9492],
        [0.4813]], dtype=torch.float64, requires_grad=True)

### Viewing Model Bias

Display the initial bias of the model.

In [22]:
model.bias

tensor([0.], dtype=torch.float64, requires_grad=True)

# **Training Pipeline**


```python 
{Steps For Training the model}

    Run loop for number of epochs
        
        - Forward Pass

        - Loss Calculation

        - Backward Pass

        - Parameter Updation



### Training the Model

Run the training loop for the specified number of epochs, performing forward pass, loss calculation, backward pass, parameter update, and zeroing gradients.

In [23]:
# define loop
for epoch in range(epochs):

    # forward pass
    y_pred = model.forward(X_train_tensor)

    # loss calculate
    loss = model.loss_function(y_pred, y_train_tensor)

    # backward pass
    loss.backward()

    # parameters update
    with torch.no_grad():
        model.weights -= learning_rate * model.weights.grad
        model.bias -= learning_rate * model.bias.grad

    # zero gradients
    model.weights.grad.zero_()
    model.bias.grad.zero_()

    # print loss in each epoch
    print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')

Epoch: 1, Loss: 3.318490211053252
Epoch: 2, Loss: 3.1843413187180274
Epoch: 3, Loss: 3.0493762309025545
Epoch: 4, Loss: 2.905680272746307
Epoch: 5, Loss: 2.7567154842096877
Epoch: 6, Loss: 2.6047233188690764
Epoch: 7, Loss: 2.4521440740004157
Epoch: 8, Loss: 2.2979173124195054
Epoch: 9, Loss: 2.1401394233993893
Epoch: 10, Loss: 1.9833513835659828
Epoch: 11, Loss: 1.8263484353931436
Epoch: 12, Loss: 1.6791133106714162
Epoch: 13, Loss: 1.5406678875720123
Epoch: 14, Loss: 1.4106071578125035
Epoch: 15, Loss: 1.2952999806076784
Epoch: 16, Loss: 1.195669017217684
Epoch: 17, Loss: 1.1117579859556574
Epoch: 18, Loss: 1.0425698866576047
Epoch: 19, Loss: 0.9862990255985655
Epoch: 20, Loss: 0.9408525238198547
Epoch: 21, Loss: 0.9042340755458559
Epoch: 22, Loss: 0.8746924207021703
Epoch: 23, Loss: 0.8507514240949334
Epoch: 24, Loss: 0.8312017499242994
Epoch: 25, Loss: 0.8150784449188188
Epoch: 26, Loss: 0.8016289081872313
Epoch: 27, Loss: 0.7902754078316684
Epoch: 28, Loss: 0.7805780557695009
Epoc

### Viewing Trained Weights

Display the weights after training.

In [24]:
model.weights

tensor([[ 0.2861],
        [ 0.1467],
        [-0.1345],
        [-0.1725],
        [ 0.2246],
        [-0.4989],
        [-0.4996],
        [-0.4149],
        [ 0.1226],
        [ 0.3324],
        [ 0.1979],
        [-0.1983],
        [ 0.4674],
        [-0.1596],
        [-0.0453],
        [ 0.0571],
        [ 0.2180],
        [ 0.2147],
        [-0.0129],
        [-0.3215],
        [-0.2870],
        [ 0.1679],
        [ 0.5709],
        [-0.0769],
        [-0.0678],
        [-0.1176],
        [ 0.0356],
        [ 0.1358],
        [ 0.3131],
        [-0.0157]], dtype=torch.float64, requires_grad=True)

### Viewing Trained Bias

Display the bias after training.

In [25]:
model.bias

tensor([-0.3325], dtype=torch.float64, requires_grad=True)

# **Evaluation**


### Evaluating the Model

Use the trained model to predict on the test set and calculate accuracy.

In [26]:
# model evaluation
with torch.no_grad():
    y_pred = model.forward(X_test_tensor)
    
    y_pred = (y_pred > 0.5).float()
    
    accuracy = (y_pred == y_test_tensor).float().mean()
    
    print(f'Accuracy: {accuracy.item()}')

Accuracy: 0.5623268485069275
